version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    command: >
      sh -c "npm install && npm run dev"
    environment:
      DATABASE_URL: postgres://myuser:mypass@db:5432/mydb
      NODE_ENV: development
    ports:
      - "3000:3000"
      - "3010:3010"
      - "24678:24678"
    # If you want to see local code changes during dev, you could do:
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres-data:
